/**
 * speedSolver.c
 *
 *    ABSTRACT:
 *      The purpose of this sfunction is to call a simple legacy
 *      function during simulation:
 *
 *         void MagicBox(SolverInput u1[1], SpeedDynParameter u2[1], EnvFactor u3[1], SolverOutput y1[1], double u4, double u5, double u6)
 *
 *    Simulink version           : 10.0 (R2019b) 18-Jul-2019
 *    C source code generated on : 25-Jun-2020 16:17:54
 *
 * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED
 */

/**
     %%%-MATLAB_Construction_Commands_Start
     def = legacy_code('initialize');
     def.SFunctionName = 'speedSolver';
     def.OutputFcnSpec = 'void MagicBox(SolverInput u1[1], SpeedDynParameter u2[1], EnvFactor u3[1], SolverOutput y1[1], double u4, double u5, double u6)';
     def.HeaderFiles = {'BasicAlgorithm.h', 'MathFunction.h', 'SystemDynamic.h', 'SolverStruct.h', 'PrintResult.h', 'BoundaryLine.h', 'AdaptiveGrid.h'};
     def.SourceFiles = {'BasicAlgorithm.c', 'MathFunction.c', 'SystemDynamic.c', 'PrintResult.c', 'BoundaryLine.c', 'AdaptiveGrid.c'};
     def.IncPaths = {'../inc/'};
     def.SrcPaths = {'../src'};
     legacy_code('sfcn_cmex_generate', def);
     legacy_code('compile', def);
     %%%-MATLAB_Construction_Commands_End
 */

/* Must specify the S_FUNCTION_NAME as the name of the S-function */
#define S_FUNCTION_NAME  speedSolver
#define S_FUNCTION_LEVEL 2

/**
 * Need to include simstruc.h for the definition of the SimStruct and
 * its associated macro definitions.
 */
#include "simstruc.h"

#include <string.h>
#include <stdlib.h>

/* Specific header file(s) required by the legacy code function */
#include "BasicAlgorithm.h"
#include "MathFunction.h"
#include "SystemDynamic.h"
#include "SolverStruct.h"
#include "PrintResult.h"
#include "BoundaryLine.h"
#include "AdaptiveGrid.h"

#define IS_SIMULATION_TARGET(S) (ssRTWGenIsAccelerator(S) || ssIsRapidAcceleratorActive(S) || ssRTWGenIsModelReferenceSimTarget(S) || (ssGetSimMode(S)==SS_SIMMODE_NORMAL) || (ssGetSimMode(S)==SS_SIMMODE_SIZES_CALL_ONLY) || !((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) && GetRTWEnvironmentMode(S)==0))


/* Utility function prototypes */
static void CheckDataTypes(SimStruct *S);
static int_T GetRTWEnvironmentMode(SimStruct *S);

/* Function: mdlInitializeSizes ===========================================
 * Abstract:
 *   The sizes information is used by Simulink to determine the S-function
 *   block's characteristics (number of inputs, outputs, states, etc.).
 */
static void mdlInitializeSizes(SimStruct *S)
{
    /* Flag for detecting standalone or simulation target mode */
    boolean_T isSimulationTarget = IS_SIMULATION_TARGET(S);

    /* Number of expected parameters */
    ssSetNumSFcnParams(S, 0);


    /* Set the number of work vectors */
    if (!IS_SIMULATION_TARGET(S)) {
        ssSetNumPWork(S, 0);
        if (!ssSetNumDWork(S, 0)) return;
    } else {
        ssSetNumPWork(S, 4);
        if (!ssSetNumDWork(S, 2)) return;

        /* Configure the dwork 1 (__dtSizeInfo) */
        ssSetDWorkDataType(S, 0, SS_INT32);
        ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
        ssSetDWorkName(S, 0, "dtSizeInfo");
        ssSetDWorkWidth(S, 0, 9);
        ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

        /* Configure the dwork 2 (__dtBusInfo) */
        ssSetDWorkDataType(S, 1, SS_INT32);
        ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_DWORK);
        ssSetDWorkName(S, 1, "dtBusInfo");
        ssSetDWorkWidth(S, 1, 66);
        ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);
    } /* if */

    /* Set the number of input ports */
    if (!ssSetNumInputPorts(S, 6)) return;

    /* Configure the input port 1 */
    #if defined(MATLAB_MEX_FILE) 
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;

        ssRegisterTypeFromNamedObject(S, "SolverInput", &dataTypeIdReg);
        if(dataTypeIdReg == INVALID_DTYPE_ID) return;

        ssSetInputPortDataType(S, 0, dataTypeIdReg);
    } /* if */
    #endif
    ssSetBusInputAsStruct(S, 0, 1);
    {
        int_T u1Width = 1;
        ssSetInputPortWidth(S, 0, u1Width);
    }
    ssSetInputPortComplexSignal(S, 0, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 0, 1);
    ssSetInputPortAcceptExprInRTW(S, 0, 0);
    ssSetInputPortOverWritable(S, 0, 0);
    ssSetInputPortOptimOpts(S, 0, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 0, 1);

    /* Configure the input port 2 */
    #if defined(MATLAB_MEX_FILE) 
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;

        ssRegisterTypeFromNamedObject(S, "SpeedDynParameter", &dataTypeIdReg);
        if(dataTypeIdReg == INVALID_DTYPE_ID) return;

        ssSetInputPortDataType(S, 1, dataTypeIdReg);
    } /* if */
    #endif
    ssSetBusInputAsStruct(S, 1, 1);
    {
        int_T u2Width = 1;
        ssSetInputPortWidth(S, 1, u2Width);
    }
    ssSetInputPortComplexSignal(S, 1, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 1, 1);
    ssSetInputPortAcceptExprInRTW(S, 1, 0);
    ssSetInputPortOverWritable(S, 1, 0);
    ssSetInputPortOptimOpts(S, 1, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 1, 1);

    /* Configure the input port 3 */
    #if defined(MATLAB_MEX_FILE) 
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;

        ssRegisterTypeFromNamedObject(S, "EnvFactor", &dataTypeIdReg);
        if(dataTypeIdReg == INVALID_DTYPE_ID) return;

        ssSetInputPortDataType(S, 2, dataTypeIdReg);
    } /* if */
    #endif
    ssSetBusInputAsStruct(S, 2, 1);
    {
        int_T u3Width = 1;
        ssSetInputPortWidth(S, 2, u3Width);
    }
    ssSetInputPortComplexSignal(S, 2, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 2, 1);
    ssSetInputPortAcceptExprInRTW(S, 2, 0);
    ssSetInputPortOverWritable(S, 2, 0);
    ssSetInputPortOptimOpts(S, 2, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 2, 1);

    /* Configure the input port 4 */
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    {
        int_T u4Width = 1;
        ssSetInputPortWidth(S, 3, u4Width);
    }
    ssSetInputPortComplexSignal(S, 3, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 3, 1);
    ssSetInputPortAcceptExprInRTW(S, 3, 1);
    ssSetInputPortOverWritable(S, 3, 1);
    ssSetInputPortOptimOpts(S, 3, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 3, 1);

    /* Configure the input port 5 */
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    {
        int_T u5Width = 1;
        ssSetInputPortWidth(S, 4, u5Width);
    }
    ssSetInputPortComplexSignal(S, 4, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 4, 1);
    ssSetInputPortAcceptExprInRTW(S, 4, 1);
    ssSetInputPortOverWritable(S, 4, 1);
    ssSetInputPortOptimOpts(S, 4, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 4, 1);

    /* Configure the input port 6 */
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    {
        int_T u6Width = 1;
        ssSetInputPortWidth(S, 5, u6Width);
    }
    ssSetInputPortComplexSignal(S, 5, COMPLEX_NO);
    ssSetInputPortDirectFeedThrough(S, 5, 1);
    ssSetInputPortAcceptExprInRTW(S, 5, 1);
    ssSetInputPortOverWritable(S, 5, 1);
    ssSetInputPortOptimOpts(S, 5, SS_REUSABLE_AND_LOCAL);
    ssSetInputPortRequiredContiguous(S, 5, 1);

    /* Set the number of output ports */
    if (!ssSetNumOutputPorts(S, 1)) return;

    /* Configure the output port 1 */
    #if defined(MATLAB_MEX_FILE) 
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;

        ssRegisterTypeFromNamedObject(S, "SolverOutput", &dataTypeIdReg);
        if(dataTypeIdReg == INVALID_DTYPE_ID) return;

        ssSetOutputPortDataType(S, 0, dataTypeIdReg);
    } /* if */
    #endif
    ssSetBusOutputObjectName(S, 0, (void *)"SolverOutput");
    ssSetBusOutputAsStruct(S, 0, 1);
    {
        int_T y1Width = 1;
        ssSetOutputPortWidth(S, 0, y1Width);
    }
    ssSetOutputPortComplexSignal(S, 0, COMPLEX_NO);
    ssSetOutputPortOptimOpts(S, 0, SS_REUSABLE_AND_LOCAL);
    ssSetOutputPortOutputExprInRTW(S, 0, 0);

    /* Register reserved identifiers to avoid name conflict */
    if (ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) {

        /* Register reserved identifier for  */
        ssRegMdlInfo(S, "MagicBox", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

        /* Register reserved identifier for wrappers */
        if (isSimulationTarget) {

            /* Register reserved identifier for  */
            ssRegMdlInfo(S, "MagicBox_wrapper_Output", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

            /* Register reserved identifier for allocating PWork for SimulationTarget */
            ssRegMdlInfo(S, "speedSolver_wrapper_allocmem", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

            /* Register reserved identifier for freeing PWork for SimulationTarget */
            ssRegMdlInfo(S, "speedSolver_wrapper_freemem", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));
        } /* if */
    } /* if */

    /* This S-function can be used in referenced model simulating in normal mode */
    ssSetModelReferenceNormalModeSupport(S, MDL_START_AND_MDL_PROCESS_PARAMS_OK);

    /* Set the number of sample time */
    ssSetNumSampleTimes(S, 1);

    /* Set the compliance for the operating point save/restore. */
    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);

    ssSetArrayLayoutForCodeGen(S, SS_ALL);

    /* Set the Simulink version this S-Function has been generated in */
    ssSetSimulinkVersionGeneratedIn(S, "10.0");

    /**
     * All options have the form SS_OPTION_<name> and are documented in
     * matlabroot/simulink/include/simstruc.h. The options should be
     * bitwise or'd together as in
     *    ssSetOptions(S, (SS_OPTION_name1 | SS_OPTION_name2))
     */
    ssSetOptions(S,
        SS_OPTION_USE_TLC_WITH_ACCELERATOR |
        SS_OPTION_CAN_BE_CALLED_CONDITIONALLY |
        SS_OPTION_EXCEPTION_FREE_CODE |
        SS_OPTION_WORKS_WITH_CODE_REUSE |
        SS_OPTION_SFUNCTION_INLINED_FOR_RTW |
        SS_OPTION_DISALLOW_CONSTANT_SAMPLE_TIME
    );

    /* Verify Data Type consistency with specification */
    #if defined(MATLAB_MEX_FILE)
    if ((ssGetSimMode(S)!=SS_SIMMODE_SIZES_CALL_ONLY)) {
        CheckDataTypes(S);
    } /* if */
    #endif
}

/* Function: mdlInitializeSampleTimes =====================================
 * Abstract:
 *   This function is used to specify the sample time(s) for your
 *   S-function. You must register the same number of sample times as
 *   specified in ssSetNumSampleTimes.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, INHERITED_SAMPLE_TIME);
    ssSetOffsetTime(S, 0, FIXED_IN_MINOR_STEP_OFFSET);

    #if defined(ssSetModelReferenceSampleTimeDefaultInheritance)
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    #endif
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)
/* Function: mdlSetWorkWidths =============================================
 * Abstract:
 *   The optional method, mdlSetWorkWidths is called after input port
 *   width, output port width, and sample times of the S-function have
 *   been determined to set any state and work vector sizes which are
 *   a function of the input, output, and/or sample times. 
 *   Run-time parameters are registered in this method using methods 
 *   ssSetNumRunTimeParams, ssSetRunTimeParamInfo, and related methods.
 */
static void mdlSetWorkWidths(SimStruct *S)
{
}
#endif

#define MDL_START
#if defined(MDL_START)
/* Function: mdlStart =====================================================
 * Abstract:
 *   This function is called once at start of model execution. If you
 *   have states that should be initialized once, this is the place
 *   to do it.
 */
static void mdlStart(SimStruct *S)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Get common data type Id */
        DTypeId __SolverOutputId = ssGetDataTypeId(S, "SolverOutput");
        DTypeId __doubleId = ssGetDataTypeId(S, "double");
        DTypeId __SolverInputId = ssGetDataTypeId(S, "SolverInput");
        DTypeId __GridSettingId = ssGetDataTypeId(S, "GridSetting");
        DTypeId __uint16Id = ssGetDataTypeId(S, "uint16");
        DTypeId __LimitSettingId = ssGetDataTypeId(S, "LimitSetting");
        DTypeId __SolverSettingId = ssGetDataTypeId(S, "SolverSetting");
        DTypeId __SpeedDynParameterId = ssGetDataTypeId(S, "SpeedDynParameter");
        DTypeId __EnvFactorId = ssGetDataTypeId(S, "EnvFactor");

        /* Get common data type size */
        __dtSizeInfo[0] = ssGetDataTypeSize(S, __SolverOutputId);
        __dtSizeInfo[1] = ssGetDataTypeSize(S, __doubleId);
        __dtSizeInfo[2] = ssGetDataTypeSize(S, __SolverInputId);
        __dtSizeInfo[3] = ssGetDataTypeSize(S, __GridSettingId);
        __dtSizeInfo[4] = ssGetDataTypeSize(S, __uint16Id);
        __dtSizeInfo[5] = ssGetDataTypeSize(S, __LimitSettingId);
        __dtSizeInfo[6] = ssGetDataTypeSize(S, __SolverSettingId);
        __dtSizeInfo[7] = ssGetDataTypeSize(S, __SpeedDynParameterId);
        __dtSizeInfo[8] = ssGetDataTypeSize(S, __EnvFactorId);

        /* Get information for accessing SolverOutput.Cost */
        __dtBusInfo[0] = ssGetBusElementOffset(S, __SolverOutputId, 0);
        __dtBusInfo[1] = __dtSizeInfo[1];

        /* Get information for accessing SolverOutput.Vo */
        __dtBusInfo[2] = ssGetBusElementOffset(S, __SolverOutputId, 1);
        __dtBusInfo[3] = 200*__dtSizeInfo[1];

        /* Get information for accessing SolverOutput.Fo */
        __dtBusInfo[4] = ssGetBusElementOffset(S, __SolverOutputId, 2);
        __dtBusInfo[5] = 200*__dtSizeInfo[1];

        /* Get information for accessing SolverOutput.upperBound */
        __dtBusInfo[6] = ssGetBusElementOffset(S, __SolverOutputId, 3);
        __dtBusInfo[7] = 201*__dtSizeInfo[1];

        /* Get information for accessing SolverOutput.lowerBound */
        __dtBusInfo[8] = ssGetBusElementOffset(S, __SolverOutputId, 4);
        __dtBusInfo[9] = 201*__dtSizeInfo[1];

        /* Get information for accessing SolverOutput.upperActual */
        __dtBusInfo[10] = ssGetBusElementOffset(S, __SolverOutputId, 5);
        __dtBusInfo[11] = 200*__dtSizeInfo[1];

        /* Get information for accessing SolverOutput.lowerActual */
        __dtBusInfo[12] = ssGetBusElementOffset(S, __SolverOutputId, 6);
        __dtBusInfo[13] = 200*__dtSizeInfo[1];

        /* Get information for accessing SolverInput.GridSize.Nx */
        __dtBusInfo[14] = ssGetBusElementOffset(S, __SolverInputId, 0) + ssGetBusElementOffset(S, __GridSettingId, 0);
        __dtBusInfo[15] = __dtSizeInfo[4];

        /* Get information for accessing SolverInput.GridSize.Nu */
        __dtBusInfo[16] = ssGetBusElementOffset(S, __SolverInputId, 0) + ssGetBusElementOffset(S, __GridSettingId, 1);
        __dtBusInfo[17] = __dtSizeInfo[4];

        /* Get information for accessing SolverInput.GridSize.Nhrz */
        __dtBusInfo[18] = ssGetBusElementOffset(S, __SolverInputId, 0) + ssGetBusElementOffset(S, __GridSettingId, 2);
        __dtBusInfo[19] = __dtSizeInfo[4];

        /* Get information for accessing SolverInput.Constraint.Vmax */
        __dtBusInfo[20] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 0);
        __dtBusInfo[21] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.Constraint.Vmin */
        __dtBusInfo[22] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 1);
        __dtBusInfo[23] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.Constraint.Fmax */
        __dtBusInfo[24] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 2);
        __dtBusInfo[25] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.Constraint.Fmin */
        __dtBusInfo[26] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 3);
        __dtBusInfo[27] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.Constraint.PAmax */
        __dtBusInfo[28] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 4);
        __dtBusInfo[29] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.Constraint.PDmax */
        __dtBusInfo[30] = ssGetBusElementOffset(S, __SolverInputId, 1) + ssGetBusElementOffset(S, __LimitSettingId, 5);
        __dtBusInfo[31] = __dtSizeInfo[1];

        /* Get information for accessing SolverInput.SolverLimit.infValue */
        __dtBusInfo[32] = ssGetBusElementOffset(S, __SolverInputId, 2) + ssGetBusElementOffset(S, __SolverSettingId, 0);
        __dtBusInfo[33] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.m */
        __dtBusInfo[34] = ssGetBusElementOffset(S, __SpeedDynParameterId, 0);
        __dtBusInfo[35] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.g */
        __dtBusInfo[36] = ssGetBusElementOffset(S, __SpeedDynParameterId, 1);
        __dtBusInfo[37] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.crr */
        __dtBusInfo[38] = ssGetBusElementOffset(S, __SpeedDynParameterId, 2);
        __dtBusInfo[39] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.CdA */
        __dtBusInfo[40] = ssGetBusElementOffset(S, __SpeedDynParameterId, 3);
        __dtBusInfo[41] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.ds */
        __dtBusInfo[42] = ssGetBusElementOffset(S, __SpeedDynParameterId, 4);
        __dtBusInfo[43] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.eta_trans */
        __dtBusInfo[44] = ssGetBusElementOffset(S, __SpeedDynParameterId, 5);
        __dtBusInfo[45] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.eta_dc */
        __dtBusInfo[46] = ssGetBusElementOffset(S, __SpeedDynParameterId, 6);
        __dtBusInfo[47] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.alpha0 */
        __dtBusInfo[48] = ssGetBusElementOffset(S, __SpeedDynParameterId, 7);
        __dtBusInfo[49] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.alpha1 */
        __dtBusInfo[50] = ssGetBusElementOffset(S, __SpeedDynParameterId, 8);
        __dtBusInfo[51] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.alpha2 */
        __dtBusInfo[52] = ssGetBusElementOffset(S, __SpeedDynParameterId, 9);
        __dtBusInfo[53] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.beta0 */
        __dtBusInfo[54] = ssGetBusElementOffset(S, __SpeedDynParameterId, 10);
        __dtBusInfo[55] = __dtSizeInfo[1];

        /* Get information for accessing SpeedDynParameter.penalty */
        __dtBusInfo[56] = ssGetBusElementOffset(S, __SpeedDynParameterId, 11);
        __dtBusInfo[57] = __dtSizeInfo[1];

        /* Get information for accessing EnvFactor.Vmax_env */
        __dtBusInfo[58] = ssGetBusElementOffset(S, __EnvFactorId, 0);
        __dtBusInfo[59] = 201*__dtSizeInfo[1];

        /* Get information for accessing EnvFactor.Vmin_env */
        __dtBusInfo[60] = ssGetBusElementOffset(S, __EnvFactorId, 1);
        __dtBusInfo[61] = 201*__dtSizeInfo[1];

        /* Get information for accessing EnvFactor.Angle_env */
        __dtBusInfo[62] = ssGetBusElementOffset(S, __EnvFactorId, 2);
        __dtBusInfo[63] = 201*__dtSizeInfo[1];

        /* Get information for accessing EnvFactor.endBlock */
        __dtBusInfo[64] = ssGetBusElementOffset(S, __EnvFactorId, 3);
        __dtBusInfo[65] = __dtSizeInfo[4];


        /* Alloc memory for the pwork 1 (__y1BUS) */
        {
            SolverOutput* __y1BUS = (SolverOutput*)calloc(sizeof(SolverOutput), ssGetOutputPortWidth(S, 0));
            if (__y1BUS==NULL) {
                ssSetErrorStatus(S, "Unexpected error during the memory allocation for __y1BUS");
                return;
            } /* if */
            ssSetPWorkValue(S, 0, __y1BUS);
        }

        /* Alloc memory for the pwork 2 (__u1BUS) */
        {
            SolverInput* __u1BUS = (SolverInput*)calloc(sizeof(SolverInput), ssGetInputPortWidth(S, 0));
            if (__u1BUS==NULL) {
                ssSetErrorStatus(S, "Unexpected error during the memory allocation for __u1BUS");
                return;
            } /* if */
            ssSetPWorkValue(S, 1, __u1BUS);
        }

        /* Alloc memory for the pwork 3 (__u2BUS) */
        {
            SpeedDynParameter* __u2BUS = (SpeedDynParameter*)calloc(sizeof(SpeedDynParameter), ssGetInputPortWidth(S, 1));
            if (__u2BUS==NULL) {
                ssSetErrorStatus(S, "Unexpected error during the memory allocation for __u2BUS");
                return;
            } /* if */
            ssSetPWorkValue(S, 2, __u2BUS);
        }

        /* Alloc memory for the pwork 4 (__u3BUS) */
        {
            EnvFactor* __u3BUS = (EnvFactor*)calloc(sizeof(EnvFactor), ssGetInputPortWidth(S, 2));
            if (__u3BUS==NULL) {
                ssSetErrorStatus(S, "Unexpected error during the memory allocation for __u3BUS");
                return;
            } /* if */
            ssSetPWorkValue(S, 3, __u3BUS);
        }

    } /* if */
}
#endif

/* Function: mdlOutputs ===================================================
 * Abstract:
 *   In this function, you compute the outputs of your S-function
 *   block. Generally outputs are placed in the output vector(s),
 *   ssGetOutputPortSignal.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Get access to Parameter/Input/Output/DWork data */
        char* u1 = (char*) ssGetInputPortSignal(S, 0);
        char* u2 = (char*) ssGetInputPortSignal(S, 1);
        char* u3 = (char*) ssGetInputPortSignal(S, 2);
        char* y1 = (char*) ssGetOutputPortSignal(S, 0);
        real_T* u4 = (real_T*) ssGetInputPortSignal(S, 3);
        real_T* u5 = (real_T*) ssGetInputPortSignal(S, 4);
        real_T* u6 = (real_T*) ssGetInputPortSignal(S, 5);

        SolverInput* __u1BUS = (SolverInput*) ssGetPWorkValue(S, 1);
        SpeedDynParameter* __u2BUS = (SpeedDynParameter*) ssGetPWorkValue(S, 2);
        EnvFactor* __u3BUS = (EnvFactor*) ssGetPWorkValue(S, 3);
        SolverOutput* __y1BUS = (SolverOutput*) ssGetPWorkValue(S, 0);

        /* Assign the Simulink structure u1 to user structure __u1BUS */
        (void) memcpy(&__u1BUS[0].GridSize.Nx, u1 +  __dtBusInfo[14],  __dtBusInfo[15]);
        (void) memcpy(&__u1BUS[0].GridSize.Nu, u1 +  __dtBusInfo[16],  __dtBusInfo[17]);
        (void) memcpy(&__u1BUS[0].GridSize.Nhrz, u1 +  __dtBusInfo[18],  __dtBusInfo[19]);
        (void) memcpy(&__u1BUS[0].Constraint.Vmax, u1 +  __dtBusInfo[20],  __dtBusInfo[21]);
        (void) memcpy(&__u1BUS[0].Constraint.Vmin, u1 +  __dtBusInfo[22],  __dtBusInfo[23]);
        (void) memcpy(&__u1BUS[0].Constraint.Fmax, u1 +  __dtBusInfo[24],  __dtBusInfo[25]);
        (void) memcpy(&__u1BUS[0].Constraint.Fmin, u1 +  __dtBusInfo[26],  __dtBusInfo[27]);
        (void) memcpy(&__u1BUS[0].Constraint.PAmax, u1 +  __dtBusInfo[28],  __dtBusInfo[29]);
        (void) memcpy(&__u1BUS[0].Constraint.PDmax, u1 +  __dtBusInfo[30],  __dtBusInfo[31]);
        (void) memcpy(&__u1BUS[0].SolverLimit.infValue, u1 +  __dtBusInfo[32],  __dtBusInfo[33]);

        /* Assign the Simulink structure u2 to user structure __u2BUS */
        (void) memcpy(&__u2BUS[0].m, u2 +  __dtBusInfo[34],  __dtBusInfo[35]);
        (void) memcpy(&__u2BUS[0].g, u2 +  __dtBusInfo[36],  __dtBusInfo[37]);
        (void) memcpy(&__u2BUS[0].crr, u2 +  __dtBusInfo[38],  __dtBusInfo[39]);
        (void) memcpy(&__u2BUS[0].CdA, u2 +  __dtBusInfo[40],  __dtBusInfo[41]);
        (void) memcpy(&__u2BUS[0].ds, u2 +  __dtBusInfo[42],  __dtBusInfo[43]);
        (void) memcpy(&__u2BUS[0].eta_trans, u2 +  __dtBusInfo[44],  __dtBusInfo[45]);
        (void) memcpy(&__u2BUS[0].eta_dc, u2 +  __dtBusInfo[46],  __dtBusInfo[47]);
        (void) memcpy(&__u2BUS[0].alpha0, u2 +  __dtBusInfo[48],  __dtBusInfo[49]);
        (void) memcpy(&__u2BUS[0].alpha1, u2 +  __dtBusInfo[50],  __dtBusInfo[51]);
        (void) memcpy(&__u2BUS[0].alpha2, u2 +  __dtBusInfo[52],  __dtBusInfo[53]);
        (void) memcpy(&__u2BUS[0].beta0, u2 +  __dtBusInfo[54],  __dtBusInfo[55]);
        (void) memcpy(&__u2BUS[0].penalty, u2 +  __dtBusInfo[56],  __dtBusInfo[57]);

        /* Assign the Simulink structure u3 to user structure __u3BUS */
        (void) memcpy(__u3BUS[0].Vmax_env, u3 +  __dtBusInfo[58],  __dtBusInfo[59]);
        (void) memcpy(__u3BUS[0].Vmin_env, u3 +  __dtBusInfo[60],  __dtBusInfo[61]);
        (void) memcpy(__u3BUS[0].Angle_env, u3 +  __dtBusInfo[62],  __dtBusInfo[63]);
        (void) memcpy(&__u3BUS[0].endBlock, u3 +  __dtBusInfo[64],  __dtBusInfo[65]);

        /* Call the legacy code function */
        MagicBox(__u1BUS, __u2BUS, __u3BUS, __y1BUS, *u4, *u5, *u6);

        /* Assign the user structure __y1BUS to the Simulink structure y1 */
        (void) memcpy(y1 +  __dtBusInfo[0], &__y1BUS[0].Cost,  __dtBusInfo[1]);
        (void) memcpy(y1 +  __dtBusInfo[2], __y1BUS[0].Vo,  __dtBusInfo[3]);
        (void) memcpy(y1 +  __dtBusInfo[4], __y1BUS[0].Fo,  __dtBusInfo[5]);
        (void) memcpy(y1 +  __dtBusInfo[6], __y1BUS[0].upperBound,  __dtBusInfo[7]);
        (void) memcpy(y1 +  __dtBusInfo[8], __y1BUS[0].lowerBound,  __dtBusInfo[9]);
        (void) memcpy(y1 +  __dtBusInfo[10], __y1BUS[0].upperActual,  __dtBusInfo[11]);
        (void) memcpy(y1 +  __dtBusInfo[12], __y1BUS[0].lowerActual,  __dtBusInfo[13]);
    } /* if */
}

/* Function: mdlTerminate =================================================
 * Abstract:
 *   In this function, you should perform any actions that are necessary
 *   at the termination of a simulation.
 */
static void mdlTerminate(SimStruct *S)
{
    if (IS_SIMULATION_TARGET(S)) {

        /* Access bus/struct information */
        int32_T* __dtSizeInfo = (int32_T*) ssGetDWork(S, 0);
        int32_T* __dtBusInfo = (int32_T*) ssGetDWork(S, 1);


        /* Free memory for the pwork 1 (__y1BUS) */
        {
            SolverOutput* __y1BUS = (SolverOutput*)ssGetPWorkValue(S, 0);
            if (__y1BUS!=NULL) {
                free(__y1BUS);
                ssSetPWorkValue(S, 0, NULL);
            } /* if */
        }

        /* Free memory for the pwork 2 (__u1BUS) */
        {
            SolverInput* __u1BUS = (SolverInput*)ssGetPWorkValue(S, 1);
            if (__u1BUS!=NULL) {
                free(__u1BUS);
                ssSetPWorkValue(S, 1, NULL);
            } /* if */
        }

        /* Free memory for the pwork 3 (__u2BUS) */
        {
            SpeedDynParameter* __u2BUS = (SpeedDynParameter*)ssGetPWorkValue(S, 2);
            if (__u2BUS!=NULL) {
                free(__u2BUS);
                ssSetPWorkValue(S, 2, NULL);
            } /* if */
        }

        /* Free memory for the pwork 4 (__u3BUS) */
        {
            EnvFactor* __u3BUS = (EnvFactor*)ssGetPWorkValue(S, 3);
            if (__u3BUS!=NULL) {
                free(__u3BUS);
                ssSetPWorkValue(S, 3, NULL);
            } /* if */
        }

    } /* if */
}

/* Function: CheckDataTypeChecksum ========================================
 * Abstract:
 *   CheckDataTypeChecksum invokes a MATLAB helper for checking the consistency
 *   between the data type definition used when this S-Function was generated
 *   and the data type used when calling the S-Function.
 */
static int_T CheckDataTypeChecksum(SimStruct *S, const char* dtypeName, uint32_T* chkRef)
{
    mxArray *plhs[1] = {NULL};
    mxArray *prhs[3];
    mxArray *err = NULL;
    const char *bpath = ssGetPath(S);
    int_T status = -1;

    prhs[0] = mxCreateString(bpath);
    prhs[1] = mxCreateString(dtypeName);
    prhs[2] = mxCreateDoubleMatrix(1, 4, mxREAL);
    mxGetPr(prhs[2])[0] = chkRef[0];
    mxGetPr(prhs[2])[1] = chkRef[1];
    mxGetPr(prhs[2])[2] = chkRef[2];
    mxGetPr(prhs[2])[3] = chkRef[3];

    err = mexCallMATLABWithTrap(1, plhs, 3, prhs, "legacycode.LCT.getOrCompareDataTypeChecksum");
    mxDestroyArray(prhs[0]);
    mxDestroyArray(prhs[1]);
    mxDestroyArray(prhs[2]);

    if (err==NULL && plhs[0]!=NULL) {
        status = mxIsEmpty(plhs[0]) ? -1 : (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
    } /* if */

    return status;
}

/* Function: CheckDataTypes ===============================================
 * Abstract:
 *   CheckDataTypes verifies data type consistency between the data type 
 *   definition used when this S-Function was generated and the data type
 *   used when calling the S-Function.
 */
static void CheckDataTypes(SimStruct *S)
{

    /* Verify Bus/StructType 'SolverOutput', specification */
    {
        uint32_T chk[] = {4255726405, 3948377713, 2610385845, 578758133};
        int_T status;
        status = CheckDataTypeChecksum(S, "SolverOutput", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'SolverOutput'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'SolverOutput' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'SolverInput', specification */
    {
        uint32_T chk[] = {3959135076, 2538283570, 1536214410, 43118964};
        int_T status;
        status = CheckDataTypeChecksum(S, "SolverInput", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'SolverInput'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'SolverInput' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'GridSetting', specification */
    {
        uint32_T chk[] = {343215609, 2324619214, 3305405510, 2459847130};
        int_T status;
        status = CheckDataTypeChecksum(S, "GridSetting", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'GridSetting'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'GridSetting' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'LimitSetting', specification */
    {
        uint32_T chk[] = {2945229082, 144841381, 2960575090, 3892000980};
        int_T status;
        status = CheckDataTypeChecksum(S, "LimitSetting", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'LimitSetting'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'LimitSetting' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'SolverSetting', specification */
    {
        uint32_T chk[] = {477761599, 4099656716, 608997350, 3420185334};
        int_T status;
        status = CheckDataTypeChecksum(S, "SolverSetting", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'SolverSetting'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'SolverSetting' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'SpeedDynParameter', specification */
    {
        uint32_T chk[] = {2605636446, 1051366581, 2731795507, 3560718853};
        int_T status;
        status = CheckDataTypeChecksum(S, "SpeedDynParameter", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'SpeedDynParameter'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'SpeedDynParameter' definition has changed since the S-Function was generated");
        }
    }

    /* Verify Bus/StructType 'EnvFactor', specification */
    {
        uint32_T chk[] = {4209867305, 1599591624, 4115271628, 2723533839};
        int_T status;
        status = CheckDataTypeChecksum(S, "EnvFactor", &chk[0]);
        if (status==-1) {
          ssSetErrorStatus(S, "Unexpected error when checking the validity of the Simulink Bus/StructType 'EnvFactor'");
        } else if (status==0) {
          ssSetErrorStatus(S, "The Simulink Bus/StructType 'EnvFactor' definition has changed since the S-Function was generated");
        }
    }
}

/* Function: GetRTWEnvironmentMode ========================================
 * Abstract:
 *   Must be called when ssRTWGenIsCodeGen(S)==true. This function
 *   returns the code generation mode:
 *       -1 if an error occurred
 *        0 for standalone code generation target
 *        1 for simulation target (Accelerator, RTW-SFcn,...)
 */
static int_T GetRTWEnvironmentMode(SimStruct *S)
{
    int_T status;
    mxArray * err;
    mxArray *plhs[1];
    mxArray *prhs[1];

    /* Get the name of the Simulink block diagram */
    prhs[0] = mxCreateString(ssGetModelName(ssGetRootSS(S)));
    plhs[0] = NULL;

    /* Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB */
    err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");

    mxDestroyArray(prhs[0]);

    /* Set the error status if an error occurred */
    if (err) {
        if (plhs[0]) {
            mxDestroyArray(plhs[0]);
            plhs[0] = NULL;
        } /* if: } */
        ssSetErrorStatus(S, "Unknown error during call to 'rtwenvironmentmode'.");
        return -1;
    } /* if */

    /* Get the value returned by rtwenvironmentmode(modelName) */
    if (plhs[0]) {
        status = (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
        plhs[0] = NULL;
    } /* if */

    return status;
}

/* Required S-function trailer */
#ifdef    MATLAB_MEX_FILE
# include "simulink.c"
#else
# include "cg_sfun.h"
#endif

